### ISSUE TITLE
Will you ever update the efi? 

### ISSUE THREAD

**Issue by Addster09** [thetredev/thinkpad13-gen2-macos#1]
Will you ever try to update the efi or try to upload a new one with Opencore?

**Comment by thetredev** [comment]
I can do that tonight.

**Comment by Addster09** [comment]
Thanks man! Will it be with Opencore or Clover?

**Comment by thetredev** [comment]
OpenCore.

**Comment by thetredev** [comment]
Done. Hope it works for you!

Also I will change the repository name and URL to https://github.com/thetredev/thinkpad13-gen2-macos (without the `-sierra` prefix), so be sure to follow that link in the future.
